query FindUniquePullRequest($where: PullRequestWhereUniqueInput!) {
  findUniquePullRequest(where: $where) {
    id
    phrase {
      id
      word
      code
      type
      index
      status
      userId
    }
    phraseId
    word
    code
    index
    type
    status
    evaluation
    _count {
      issue
      likes
      dislikes
    }
    updateAt
    createAt
  }
}
