mutation TogglePullRequestEvaluation(
  $where: PullRequestWhereUniqueInput!
  $data: PullRequestEvaluationData!
) {
  togglePullRequestEvaluation(where: $where, data: $data) {
    id
    evaluation
  }
}
